services:
  python-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: python-dev
    volumes:
      - ../.:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - kafka
      - minio
      - clickhouse

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: erp_db
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    ports:
      - "9092:9092"
    # volumes:
    #   - kafka-data:/var/lib/kafka/data

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    # volumes:
    #   - minio-data:/data

  clickhouse:
    image: clickhouse:latest
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
      CLICKHOUSE_DB: commerce
    ports:
      - "8123:8123"
      - "9009:9009"
    # volumes:
    #   - clickhouse-data:/var/lib/clickhouse

# volumes:
#   postgres-data:
#   kafka-data:
#   minio-data:
#   clickhouse-data: